export const ADD_CARD = "ADD_CARD"
export const DELETE_CARD = "DELETE_CARD"
export const NEW_SEARCH = "NEW_SEARCH"
export const ADD_DECK = "ADD_DECK"
export const DECK_TO_COLL = "DECK_TO_COLL"
export const COLL_TO_DECK = "COLL_TO_DECK"